### ISSUE TITLE
Actividad 1_mapa mental 

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Jaczibeth#1]
Jaczibeth Cruz 1bs
![MAPA MENTAL_INVESTIGACION DOCUMENTAL](https://user-images.githubusercontent.com/112178026/188514640-d05f53f1-f47e-447a-a00f-7bc6297d4a4d.jpg)

**Comment by 11042002** [comment]
Tu calificación es de: 18.8

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
